### ISSUE TITLE
Not an issue, just a question....

### ISSUE THREAD

**Issue by proemke** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#1]
Hi bbqkees,

Do you know how much current can be pulled from the EMS front service jack connector? 
I'm planning to make a pcb with an ESP8266 module to push the data to a MQTT broker. 
I want to convert the 12V to 3.3V, if enough current is available then an external power source won't be needed.

Best regards,
Edjeed

Ps. Sorry for abusing the issue page, didn't know where to ask else...
I am not able to measure myself, don't have a Nefit yet (but will be having one soon)

**Comment by bbqkees** [comment]
Nefit sells a Wifi service module that connects only to that plug. So maybe
there is enough current available for an ESP.
You would have to try though. The ESP may draw i believe about 300mA on 3v.
