### ISSUE TITLE
Bosch EasyControl Adapter 

### ISSUE THREAD

**Issue by wlemkens** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#11]
I'm new to this, and I cannot get on the domoticz forum because a cookie policy I need to accept that isn't visible to me. But there is an adapter for older thermostats that has EMS on the thermostat side and connects to the older heating system. (I assume the protocol of interest on that side is called iRT) 

This makes my Buderus logamax U122 compatible with the Bosch EasyControl CT200, which according to the documentation, is using EMS.

So that might extent the usability of this project to more heating systems.

**Comment by bbqkees** [comment]
That adapter is mainly used to allow the Easy thermostat control older boilers. Although I have not tested it, I don't think it will convert (a lot of) messages from the boiler to the bus itself. 
Perhaps you can try to see which datagrams are exactly transmitted on the bus. If there is a message type 0x18 UBAMonitorSlow observed it would make it compatible with the main sketch on my EMS Github page.
