### ISSUE TITLE
Rx Tx label

### ISSUE THREAD

**Issue by nsine-zz** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#12]
Is it possible that the rx & tx label on the v0.9 board is switched?
I have to connect the rx pin from the ems module to the rx pin on the arduino mega to get the whole thing working.

**Comment by bbqkees** [comment]
It is not switched.
Indeed connect RX of the board to RX of the Mega. It's also noted like that in the instruction sheet included with the board.
If you connect two devices via a serial port directly you would indeed normally connect the RX from one device to TX from the other.
However, the board is basically only a logic level shifter. So you need to see it as an extension of the controller, not as the other side.
At least, that was my idea behind it.

**Comment by nsine-zz** [comment]
Ok, thank you for sorting it out.
