### ISSUE TITLE
How can I write values?

### ISSUE THREAD

**Issue by lobocobra** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#16]
I have a Buderus GB125 oil heating and have the EMS Bus interface board and the WEMOS. I can telnet to the WEMOS and see all data like expected.

**What I want to do**
I would like to change the temperatures on my Buderus GB125 and set the night / day status

**What I tried**
I telnet to wemos and saw that the 2 commands should do the trick:
thermostat mod 0 
thermostat temp 23
=> I would now expect that my RC35 switches to night mode and temp changes to 23°
=> But nothing is changed in the RC35

**Hints needed**
Does it not work with RC35? Can somebody say it?
Do I have to create a telegram ? How Can I send it?
https://emswiki.thefischer.net/doku.php?id=wiki:ems:telegramme

Many thanks for some hints to be able to change settings.

**Comment by lobocobra** [comment]
It seems that the data is written but my RC35 does not change thestatus.
Example:
If I set the heating manually to night mode, my rc35 keeps showing auto mode.
=> same if I set temperature.

Is this a problem with the RC35, that it does not listen to the BUS and thus the RC35 shows the old (overwritten) data?

Does anyone know this?

**Comment by lobocobra** [comment]
A probable cause could be that my house has a floor-heating and the used circuit is NR2.
=> I currently try to send telegram but, I have problems to find plausible values.

If anyone  managed to change day/night or the temperature, please give me a hint...

**Comment by lobocobra** [comment]
I found the solution...
The problem was that this code assumes that you have 1 circuit.
=> but if you have a floor heating it is circuit 2.

To change the day / night status you need to.... 
send 0b 90 47 07 01  => to show the current status
send 0b 10 47 07 02 => to set the status on automatic (2)

means you need to find out the codes... go here....
https://emswiki.thefischer.net/doku.php?id=wiki:ems:telegramme#schaltzeiten_allgemein

**Comment by proddy** [comment]
For the record, the code was designed that way and its clearly mention in the documenaton [here](https://github.com/proddy/EMS-ESP#which-thermostats-are-supported) _"RC35 with support for the 1st heating circuit (HC1)"_. Why don't you contribute and extend the code to support the other HCs?

**Comment by lobocobra** [comment]
I am on it :)
=> Just wanted to leave a trace here for others so that they might use it.
