### ISSUE TITLE
Lost connection and capacitor C1 very hot

### ISSUE THREAD

**Issue by kkberg** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#20]
After letting it work for some time, connection to EMS-Bus is lost and one capacitor is getting very hot. It's C1 on the pcb. I disconnected the board asap from the service connector jack, Connecting it again for only 2 swconds it's hoz again. I think a part on the pcb is damaged. I'm really frustrated that it only worked for a very short time. What could be happened to cause this?

**Comment by bbqkees** [comment]
Can you email me a picture of the PCB?
Lets take it up from there.

**Comment by kkberg** [comment]
Which email shall I use?

**Comment by kkberg** [comment]
sent it to 'bbqkees+pcb..........'
