### ISSUE TITLE
EBUS or EMS?

### ISSUE THREAD

**Issue by barsmedia** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#9]
Hello!
I have old Junkers atmospheric boiler (ZWC28-1MF2K) and stumbled in docs about using E/BUS devices (thermostats etc.), so the question is:
Does EMS is the same as EBUS older Junkers (Bosch) used?
Also I have started upgrade my heating system (step by step), and have 2 MM100 controllers (for floor/radiators heating accordingly) that are 100% EMS devices, was thinking about creating virtual thermostats from sensors I have in my house -- is it possible?

**Comment by bbqkees** [comment]
The EMS bus is something else.

If you know a bit of programming and can take the time to reverse engineer the MM100 than maybe yes.
But I guess the MM100 are also EMS slave devices so you still need an EMS master in the circuit, which would be the boiler.
